services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
    networks:
      - wallet-network

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://auth_user:auth_password@postgres:5432/auth_db
    depends_on:
      postgres:
        condition: service_healthy # Wait for Postgres health check
    networks:
      - wallet-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    healthcheck: # Add health check to ensure Postgres is ready
      test: ["CMD", "pg_isready", "-U", "auth_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
