version: "3.9"
services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./services/auth-service
    command: npm run dev # Use nodemon for hot reload
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://auth_user:auth_password@postgres:5432/auth_db
    volumes:
      - ./services/auth-service:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
