version: "3.8"

services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
