name: CI - Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          working-directory: services/userprofile-service

      - name: Install Dependencies
        run: npm install
        working-directory: services/userprofile-service

      - name: Run Linter
        run: npm run lint
        working-directory: services/userprofile-service

      - name: Run Tests
        run: npm test
        working-directory: services/userprofile-service

      - name: Build Docker Image
        run: docker build -t userprofile-service .
        working-directory: services/userprofile-service
